import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Col, Container, Row } from 'react-bootstrap'
import styles from '../styles/Home.module.css'
import Cards from '../components/Cards'
const Home: NextPage = () => {
  return (
    <Container fluid>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row className={styles.main}>
        <Col className={styles.text}>
        <h1>Adote um aumigo amigo próximo de você</h1>
        <h6>ou ajude organizações em todo o Brasil</h6>
        </Col>
        <Col>
          <Image src={"/img/vira-lata-caramelo.png"} alt="Vira lata caramelo com carinha super fofa olhando para frente" width={847} height={609} />
        </Col>
      </Row>
      <Row className={styles.cards}>
        <h2>HISTÓRIAS DE AMOR</h2>
        <Cards
         nome="Chico" 
         url='/../public/img/chico.png'
         text="Lorem ipsum dolor sit amet. Ut veniam optio est dolorum inventore sed voluptas corporis id sunt explicabo."
         adotado={true}
         onClick={""}
         />
      </Row>
    </Container>
  )
}

export default Home
